name: "Proses CI dalam membangun dan sebarkan hasil pembangunan"
on:
  push:
    branches:
      - UthabitiKachina
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: "Cek keluar..."
      - name: "Konfigurasi Sertifikasi Git"
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: "Instalasi Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: "Memasang depensi: mkdocs-material, mkdocs-static-i18n, mkdocs[i18n]"
        run: "pip install mkdocs-material mkdocs-static-i18n mkdocs[i18n]"
      - name: "Cache???"
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Pemasangan Pages
        uses: actions/configure-pages@v5
      - name: "Menjalankan pembangunan"
        run: mkdocs build
      - name: Unggah artefak
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Sebarkan hasil ke Github Pages
        id: deployment
        uses: actions/deploy-pages@v4